default: &default
  adapter: mysql2
  encoding: utf8
  charset: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password:
  socket: /tmp/mysql.sock
  timeout: 5000

development:
  <<: *default
  database: kostarika_development

test:
  <<: *default
  database: kostarika_test

production:
  <<: *default
  database: kostarika_production
